dist: trusty
language: node_js
node_js:
    - "10"
env:
    - CXX=g++-4.8

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8

install:
    - yarn add -D vuepress
    - yarn docs:build

script:
    - ./deploy.sh

cache:
    directories:
        - "node_modules"

notifications:
    email: false

deploy:
    provider: pages
    fqdn: open-dc-grid.org
    skip-cleanup: true
    github-token: $GH_REPO_TOKEN
    local_dir: master
    target_branch: master
    keep-history: false
    on:
        all_branches: true
